### ISSUE TITLE
USER STORY: Exporting voting details

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/agile-project#5]
In order to **view total of votes** as a **web admin**, I can **export the votes to a Google Sheet*

## Acceptance Criteria: 

* Export button is available on the admin dashboard
* All voting details are populated on a Google Sheet in organised columns 

## Tasks:

- [ ] Design export button
- [ ] Write Python code to pull voting details
- [ ] Write Python code to populate selected columns on the Google Sheet
